### ISSUE TITLE
Guacamole 1.5.4 and SSL

### ISSUE THREAD

**Issue by londeril** [flcontainers/guacamole#100]
Hi :)

First of all: Thanks for creating this dockerfile! It works like a charm on my test infrastructure. We are currently testing it internally but I think we'll deploy this for our supporters in the field!

Two questions: 
1) Will you be updating this Dockerfile to 1.5.4? (edit: I'm sorry... I didn't realize that 1.5.4 only got released a few days ago... sorry for that 🙈)
2) Are you planning on implementing (self-signed) SSL for this Docker? (I could use it with our reverse proxy; but since we'd like to keep this behind a VPN anyway, a self-signed cert would be more than enough)

Cheers

Daniel

**Comment by MaxWaldorf** [comment]
I am updating dev branch as we speak...

The testing container should be available in a bit...

As per reverse proxy, as I am using kubernetes with traefik so I don't have much appetite to do it...
