### ISSUE TITLE
Prevent startup errors

### ISSUE THREAD

**Issue by daberlin** [flcontainers/guacamole#101]
Hi
During container startup I (and probably everybody else) get 13 lines of rm errors caused by filefs/usr/local/bin/_startup.sh:

`rm: can't remove '/config/guacamole/extensions/guacamole-auth-duo-*.jar': No such file or directory`
`rm: can't remove '/config/guacamole/extensions/guacamole-auth-header-*.jar': No such file or directory`
...
...

Patch:
[_startup.sh.patch](https://github.com/flcontainers/guacamole/files/13687046/_startup.sh.patch)

**Comment by MaxWaldorf** [comment]
Please propose PR if needed
