### ISSUE TITLE
Allow overriding guacamole config with ENV vars

### ISSUE THREAD

**Issue by daberlin** [flcontainers/guacamole#102]
Hi
I'd suggest to add `enable-environment-properties: true` to the guacamole.properties file, so that one can set environment variables (e.g. in docker compose or elsewhere); see [guacamole-properties](https://guacamole.apache.org/doc/gug/configuring-guacamole.html#guacamole-properties).

**Comment by MaxWaldorf** [comment]
The file is persistent so you can add it afterwards...
