### ISSUE TITLE
Some packages fail in build with new release Alpine v3.19

### ISSUE THREAD

**Issue by willyamcts** [flcontainers/guacamole#103]
Hi people,

With Alpine latest = 3.19 (released recently in 07 december) the download the package `tomacat` v9.0.80 not available now, only v9.0.83 and v9.0.84 https://dlcdn.apache.org/tomcat/tomcat-9/

Too package `openssl1.1-compat-dev` not available, my workarround is change alpine version by 3.18.5 and change version tomcat...

For Alpine:
```
# vi Dockerfile
--ARG ALPINE_BASE_IMAGE=latest
++ARG ALPINE_BASE_IMAGE=3.18.5
FROM alpine:${ALPINE_BASE_IMAGE} AS builder
```

For Tomcat:
```
# vi Dockerfile +225
--ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.80/bin/apache-tomcat-9.0.80.tar.gz /tmp/
--RUN tar xvzf /tmp/apache-tomcat-9.0.80.tar.gz --strip-components 1 --directory /opt/tomcat
++ADD https://dlcdn.apache.org/tomcat/tomcat-9/v9.0.84/bin/apache-tomcat-9.0.84.tar.gz /tmp/
++RUN tar xvzf /tmp/apache-tomcat-9.0.84.tar.gz --strip-components 1 --directory /opt/tomcat
```

**Comment by MaxWaldorf** [comment]
Is the underlying HW a Nas provider?

**Comment by willyamcts** [comment]
> Is the underlying HW a Nas provider?

Sorry, I don't know if I understood your question correctly.
But the host is a VM on Proxmox VE on a local network
