### ISSUE TITLE
update to 1.5.4

### ISSUE THREAD

**Issue by celevra** [flcontainers/guacamole#108]
Hi,

in 1.5.3 json-auth is broken.
Could you update the container to 1.5.4?
I can't use the default container, cause i'm on arm64

regards and thanks for your work

**Comment by justinKocian** [comment]
Based on the Dockerfile, looks like it’s on the newest version of Guac - [1.5.4](https://guacamole.apache.org/releases/1.5.4/)

**Comment by celevra** [comment]
ah then the documentation is wrong
https://github.com/flcontainers/guacamole/blob/main/README.md?plain=1 
Line 62 talks about 1.5.3

thank you
