### ISSUE TITLE
Extensions are not copied?

### ISSUE THREAD

**Issue by galbitz** [flcontainers/guacamole#114]
I could be misunderstanding the flow but what I noticed is that:
* The environment variable GUACAMOLE_HOME is set to /app/guacamole [here](https://github.com/flcontainers/guacamole/blob/6da5aab831abaa2c32851fbe9075d362b2277de4/Dockerfile#L180) in the Dockerfile
* Later it's [set to ](https://github.com/flcontainers/guacamole/blob/6da5aab831abaa2c32851fbe9075d362b2277de4/Dockerfile#L297) /config/guacamole

When the container runs, it tries to  [copy](https://github.com/flcontainers/guacamole/blob/6da5aab831abaa2c32851fbe9075d362b2277de4/filefs/usr/local/bin/_startup.sh#L57) the extensions from /config/guacamole but they really are in /app/guacamole. This results in the extensions not copied to the right directory 

Obviously it can easily be overwritten by passing in an environment variable at container start up but I do wonder if it's intentional.

**Comment by MaxWaldorf** [comment]
fixed in 1.5.5

**Comment by galbitz** [comment]
@MaxWaldorf Confirmed, it works now. Thanks for the fix.
