### ISSUE TITLE
RDP + SFTP not working

### ISSUE THREAD

**Issue by raffnix204** [flcontainers/guacamole#115]
Hi,

Thanks for the image, everything works very good exept RDP + SFTP connection for data sharing / drag&drop.
I searched a while what the problem could be and then found out that its a bug in this version of guacamole that got fixed in version 1.5.5 - https://issues.apache.org/jira/browse/GUACAMOLE-1140
Would it be possible that you update your image to 1.5.5 where the problem is fixed?

regards

**Comment by MaxWaldorf** [comment]
as soon as 1.5.5 is out officially yes...

**Comment by raffnix204** [comment]
Ah ok sorry i oversaw that its not released yet, thx for the quick answer, good to know that you will update it asap.

**Comment by raffnix204** [comment]
1.5.5 is now released, do you already have planned when you will update your image to it? @MaxWaldorf

**Comment by raffnix204** [comment]
its working on beta container, thx!

**Comment by MaxWaldorf** [comment]
1.5.5 is out...
