### ISSUE TITLE
invalid login

### ISSUE THREAD

**Issue by kitkat0981** [flcontainers/guacamole#118]
fresh install today and keep getting invalid login with the default guacadmin/guacadmin
not sure why this is happening, any help would be appreciated.

**Comment by yanneksevinc** [comment]
same...

**Comment by PrototypeActual** [comment]
I was trying to get this working on TrueNAS Scale via their Custom apps method. If you're going for the same thing, verify  the storage permissions so the container can save to it.

The container may be trying to save the needed configuration files but not have access or sufficient permissions to do so

**Comment by MaxWaldorf** [comment]
please try 1.5.5 as I refactored it completely... But can't fix it more than I did... Sorry
