### ISSUE TITLE
ENV settings for external postgres db.

### ISSUE THREAD

**Issue by archef2000** [flcontainers/guacamole#119]
I have an external postgres db for guacamole and would like use it for guacamole and disable the start of the internal postgres db via an env.

**Comment by MaxWaldorf** [comment]
I would recommend to use the official one then...

**Comment by archef2000** [comment]
I like the buildin guacd + extentions.

**Comment by MaxWaldorf** [comment]
Sorry will not implement it but you can edit the guacamole.properties in /config/guacamole/ folder...
