### ISSUE TITLE
record sessions

### ISSUE THREAD

**Issue by TomDeSchutter** [flcontainers/guacamole#130]
Not an issue per se but I can 't figure out how I can enable session recording?
Is the feature included in the image?

**Comment by MaxWaldorf** [comment]
ffmpeg is included so it should work but please refer to guac documentation...

**Comment by TomDeSchutter** [comment]
Thx for the fast reply. 

I should rephrase my problem: I've added the extension, edited the connection to record - which it does. The container does actually save files, but I'm unable to open them and they don't show up in the history tab in order to replay them.

**Comment by TomDeSchutter** [comment]
I'll be damned, I checked those permissions multiple times. Didn't notice the permissions weren't set in the subtree. 
Thank you for the assistance!
