### ISSUE TITLE
Guacamole does not work on Raspberry Pi 4

### ISSUE THREAD

**Issue by ppiwowar** [flcontainers/guacamole#131]
Docker-compose.yml:
------------------------------
services:
    guacamole:
      image: flcontainers/guacamole:latest
      container_name: guacamole
      restart: always
      volumes:
      - '/home/pi/config:/config'
      ports:
      - 8080:8080
      environment:
        - /etc/localtime:/etc/localtime:ro
        - TZ=EUROPE/WARSAW
      platform: linux/arm64
---------------------------------

docker-compose up -d runs with no errors and I can see in Portainer docker guacamole running ok.
I can not access Guacamole on IP:8080 and the port 8080 is not open.

**Comment by ppiwowar** [comment]
Appropriate indentation in docker-compose.yml has been lost here. Please assume it is ok.

**Comment by david-kalbermatten** [comment]
this `/etc/localtime:/etc/localtime:ro` is supposed to be a volume bind, not an env var...

**Comment by MaxWaldorf** [comment]
No issues here in similar setup...
