### ISSUE TITLE
Invalid login on version 1.5.5

### ISSUE THREAD

**Issue by Raymondmax** [flcontainers/guacamole#135]
guacamole verison: 1.5.5
 
Issue: unable to login to the web UI with user guacadmin and password guacadmin, prompting invalid login.

I have checked the password_hash in the table guacamole_user, the value is `0xCA458A7D494E3BE824F5E1E175A1556C0F8EEF2C2D7DF3633BEC4A29C4411960`

can you help me check why it can not login?

**Comment by MaxWaldorf** [comment]
Impossible to reproduce...

**Comment by ovizii** [comment]
I had trouble upgrading an older version so I started fresh with version 1.5.5 of this container. Unfortunately, as the original poster here I cannot login using the default credentials guacadmin:guacadmin 

I tried deleting all data and starting fresh with v1.4.3 but am getting this error:

```
docker compose up -d
[+] Running 1/1
 ✘ guacamole Error manifest for flcontainers/guacamole:1.4.3 not found: manifest unknown: manifest unknown                                                                                                     2.2s
Error response from daemon: manifest for flcontainers/guacamole:1.4.3 not found: manifest unknown: manifest unknown
```

I then started testing with v1.5.0 upwards until v1.5.5 and all of them give me the same issue not allowing me to log in.

I see no errors in the docker logs but in the browser console I see:

`POST https://sub.domain.tld/api/tokens 403 (Forbidden) `

and if I open that link in another browser tab:

```
HTTP Status 405 – Method Not Allowed
Type Status Report

Message Method Not Allowed

Description The method received in the request-line is known by the origin server but not supported by the target resource.

Apache Tomcat/9.0.91
```

Any ideas?

**Comment by ovizii** [comment]
I am getting closer to the root of the problem. The error is indeed correct. I have a same-origin referrer policy, but why is guacamole trying to reach out to its internal IP? The IP is correct but why? If it matters, I am behind traefik as reverse proxy.


![image](https://github.com/user-attachments/assets/8dca0432-b489-4b88-a268-ef17c24c6f23)

**Comment by MaxWaldorf** [comment]
I cannot repro so unable to fix...

You can open a new issue but I will be on the same conclusion...

**Comment by virtualex-itv** [comment]
Darn.  Curious how are you testing?  I find it hard to fathom that numerous people are reporting this issue on fresh installs but you cannot reproduce.  Further testing...I just spun up a test Ubuntu VM, deployed docker, then deployed guacamole and attempted login.  Same issue, invalid login. For me, that is two separate fresh environments (rasp pi/vmware) and fresh deployments of guacamole, with the same outcome.  If I can provide you with anything to look at pls let me know.

**Comment by MaxWaldorf** [comment]
can you run it without storage attached?

**Comment by GauriSpears** [comment]
Recently I've had the same problem but removing of /opt/tomcat/.guacamole folder helped me. I had that folder with guacamole.properties inside containing `basic-user-mapping: /etc/guacamole/user-mapping.xml` but looks like it didn't work. Maybe it's not your case but I just put it here to help others.

**Comment by ovizii** [comment]
Sorry for the delay, I was trying to get this up and running before going on holiday but got stuck with this issue. I'm back now and will open a new issue to get this solved.
