### ISSUE TITLE
postgresql permission probs after upgrade from 1.3 to 1.4

### ISSUE THREAD

**Issue by ovizii** [flcontainers/guacamole#14]
hi there,

all I did was change my docker-compose.yml file to reflect the new image version and now when starting i see this error repeating endlessly:

```
guacamole    | Starting postgres...                                                                                                                  
guacamole    | postgres: could not access directory "/config/postgres": Permission denied                                                            
guacamole    | /var/run/postgresql:5432 - no response                                                                                                
guacamole    | Waiting for postgres to come up...                                           
```

This is definitely a problem with the permissions of the mounted volume for postgresql:

```
    volumes:                                                                                                                                         
      - './data:/config'                                                                                                                             
      - './shared-folder:/tmp/shared-folder'   
```

has anything changed regarding the users which run guacamole or postgres inside your image?

if I start 1.3 I see these permissions
```
ls -aln data/                                                                                                      
drwx------ 19  103 105 26 Jan 26 15:07 postgres 
```

and with 1.4 
```
ls -aln data/                                                                                                      
drwx------ 19  102 104 26 Jan 26 15:07 postgres 
```

so it looks like the user/group IDs have changed but for some reason 1.4 still fails even though when I simply change my docker-compose.yml file to use 1.3 again, the folder permissions get immediately reset and it all works.

Open for any ideas. Did anyone manage to straight upgrade from 1.3 to 1.4?

Might very well be related to https://github.com/MaxWaldorf/guacamole/issues/13

**Comment by MaxWaldorf** [comment]
I did on my end but I only have /config folder mapped...

**Comment by MaxWaldorf** [comment]
Image is based on debian...
What is your host linux distro?

**Comment by ovizii** [comment]
> I did on my end but I only have /config folder mapped...
> 

`- './shared-folder:/tmp/shared-folder' ` shouldn't matter as the error clearly states: 
`postgres: could not access directory "/config/postgres": Permission denied`

my host is running Debian 11.
I'm currently executing docker-compose up -d as root. 
I'd be willing to reset permissions, I would just really like to not lose all the settings and connections I have configured in guacamole.  

I'm happy to do something like this if you think it'll help, amusing that when starting the image, it will sort out its own permissions?
```
chown -R root:root guacamole/ 
chmod -R 770 guacamole/ 
```

the folder guacamole contains the mapped data folder, the mapped shared-folder and docker-compose.yml

**Comment by MaxWaldorf** [comment]
here are the UID and GID of postgres inside the container:
`postgres:x:102:104:PostgreSQL`

Make sure you put those from your host perspective chown -R 102:104 config/postgres...

**Comment by ovizii** [comment]
> here are the UID and GID of postgres inside the container: `postgres:x:102:104:PostgreSQL`
> 
> Make sure you put those from your host perspective chown -R 102:104 config/postgres...

Correct. I posted those above. 

The curios thing is, when I change docker-compose.yml to reflect: maxwaldorf/guacamole:1.3 the permissions of the data/postgres folder get immediately changed to 103:105 and when I edit docker-compose.yml to reflect maxwaldorf/guacamole:1.4 the permissions of the data/postgres folder get immediately changed to 102:104 

so the question that arises is why does postgres still complain??? 

anyway, I thought it was related to postgres not having permissions on the parent folder of the postgres folder so I gave it some and now I get this error:

```
guacamole    | Waiting for postgres to come up...                                                                                                    
guacamole    | 2022-01-26 15:03:20.786 UTC [321] FATAL:  the database system is starting up                                                          
guacamole    | /var/run/postgresql:5432 - rejecting connections     
```

**Comment by MaxWaldorf** [comment]
can you check your guacamole config file?
any fancy setting pointing to something else then 127.0.0.1?

**Comment by ovizii** [comment]
> can you check your guacamole config file? any fancy setting pointing to something else then 127.0.0.1?

I assume you mean data/guacamole/guacamole.properties? 
Here is its content (minus the secretkeys and such) 

```
postgresql-hostname: localhost                                                                                                                       
postgresql-port: 5432                                                                                                                                
postgresql-database: guacamole_db                                                                                                                    
postgresql-username: guacamole                                                                                                                       
postgresql-password: null                                                                                                                           
                                                                                                                                                   
duo-api-hostname: api-secret0.duosecurity.com                                                                                                       
duo-integration-key: secret    1                                                                                                        
duo-secret-key: secretw
duo-application-key: secret3                                                                
                                                                                                                                                     
enable-clipboard-integration: true                                                                                                                   
enable-websocket: true                        
```




oh, btw, docker-compose.yml is also showing some extra warnings about other instances of postmaster running, etc. - this is right after a fresh start 

```
guacamole    | [services.d] starting services                                                                                                        
guacamole    | Starting postgres...                                                                                                                  
guacamole    | Starting guacamole guacd...                                                                                                           
guacamole    | [services.d] done.                                                                                                                    
guacamole    | /var/run/postgresql:5432 - no response                                                                                                
guacamole    | Waiting for postgres to come up...                                                                                                    
guacamole    | guacd[271]: INFO:        Guacamole proxy daemon (guacd) version 1.4.0 started                                                         
guacamole    | guacd[271]: INFO:        Listening on host 0.0.0.0, port 4822                                                                         
guacamole    | /var/run/postgresql:5432 - no response                                                                                                
guacamole    | Waiting for postgres to come up...                                                                                                    
guacamole    | 2022-01-26 15:08:34.323 UTC [270] LOG:  listening on IPv4 address "127.0.0.1", port 5432                                              
guacamole    | 2022-01-26 15:08:34.323 UTC [270] LOG:  could not bind IPv6 address "::1": Cannot assign requested address                            
guacamole    | 2022-01-26 15:08:34.323 UTC [270] HINT:  Is another postmaster already running on port 5432? If not, wait a few seconds and retry.    
guacamole    | 2022-01-26 15:08:34.810 UTC [270] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"                                  
guacamole    | 2022-01-26 15:08:36.442 UTC [285] LOG:  database system was interrupted; last known up at 2022-01-26 15:03:30 UTC                     
guacamole    | 2022-01-26 15:08:36.445 UTC [286] FATAL:  the database system is starting up                                                          
guacamole    | /var/run/postgresql:5432 - rejecting connections                                                                                      
guacamole    | Waiting for postgres to come up...                                                                                                    
guacamole    | 2022-01-26 15:08:37.450 UTC [289] FATAL:  the database system is starting up                                                          
guacamole    | /var/run/postgresql:5432 - rejecting connections                                                                                      
guacamole    | Waiting for postgres to come up...                                                                                      
```

**Comment by MaxWaldorf** [comment]
I am tempted to revamp all of that and refactor completely the dockerfile and get rid of the S6 overlay stuff but it will take time...

Don't know yet how long it will take.
Can you try without mapping volume and see if without storage it works?

**Comment by ovizii** [comment]
> I am tempted to revamp all of that and refactor completely the dockerfile and get rid of the S6 overlay stuff but it will take time...
> 
> Don't know yet how long it will take. Can you try without mapping volume and see if without storage it works?

First of all let me thank you for trying to help. guacamole isn't anything extremely important for me right now, so take you time. I simply use it to access a work station at home remotely. I do have other means of access. 

I will try without mapping and report back. 

Regarding websockets, I can't remember. I have been using guacamole a long time, might have been a left-over? 
I just googled and it seems websockets are enabled by default since guacamole 0.9.4 so I guess I can remove that setting?

**Comment by MaxWaldorf** [comment]
If you use it on an x64 intel based, you can always go to:
[Official Docker Tutorial](https://guacamole.apache.org/doc/gug/guacamole-docker.html)

Actually, I could convert the the images to an arm64...

**Comment by ovizii** [comment]
it works now. I fiddled around, not sure what made it work but I changed ownership of the base folder to 102:root and same for the mapped folder data (data maps to /config)

**Comment by ovizii** [comment]
> If you use it on an x64 intel based, you can always go to: [Official Docker Tutorial](https://guacamole.apache.org/doc/gug/guacamole-docker.html)
> 
> Actually, I could convert the the images to an arm64...

I know but the official instructions used to be very convoluted so I just oznu's image and then ended up using yours :-)

**Comment by ovizii** [comment]
most probably a problem on my end since nobody else reported this.

**Comment by MaxWaldorf** [comment]
I just compiled the image a couple hours ago...

Let's see...

**Comment by ovizii** [comment]
Let me re-open this. I am trying to go from 1.4.3 to the latest 1.5.5 now.

This is my docker log:

```
 docker compose logs -f
guacamole  | DB exisit
guacamole  | postgresql-password found in /config/guacamole/guacamole.properties and exported
guacamole  | Running startup scripts
guacamole  | Preparing Config Folder
guacamole  | Applied owners rights on Postgres folder...
guacamole  | Init DB Check
guacamole  | Post startup DB scripts
guacamole  | Guacamole client waiting for DB
guacamole  | mkdir: can't create directory '/config/postgres': Permission denied
guacamole  | Guacamole client waiting for DB
guacamole  | Guacamole client waiting for DB
```

The above error makes no sense to me. Its says it applied owner rights on Postgres folder and then alter “Permission denied” !?!?

Anyone willing to share what permissions the folder mapped to /config needs?

I'd love to go back to v1.3.1 as that was working for me but I get this error:

 docker compose up -d
[+] Running 1/1
 ✘ guacamole Error manifest for flcontainers/guacamole:1.3.1 not found: manifest unknown: manifest unknown                                                                                                     2.2s
Error response from daemon: manifest for flcontainers/guacamole:1.3.1 not found: manifest unknown: manifest unknown


This is strange. Once I replace it in my docker-compose.yml with v1.5.5 it pulls the image and starts up with the previously mentioned permissions problem.

```
services:

# https://github.com/flcontainers/guacamole
  guacamole:
    image: flcontainers/guacamole:1.5.5
    container_name: guacamole
    hostname: guacamole
    networks:

```

I'd appreciate any pointers here.

**Comment by ovizii** [comment]
Btw. I gave up and started from scratch with v1.5.5 
Hitting the problem that login with guacadmin:guacadmin doesn't work. Will continues over here: https://github.com/flcontainers/guacamole/issues/135
