### ISSUE TITLE
container not starting when auth-duo is insatlled

### ISSUE THREAD

**Issue by ShlomiD83** [flcontainers/guacamole#141]
Hi,
Tried spinning up a new instance with "auth-duo" installed but after the first login i get this error.
this doesn't happen if I choose "auth-totp" for example.
the logs show no errors.

please advise.
![image](https://github.com/user-attachments/assets/3af0010b-9fef-4046-be1b-9e7e53570d46)

**Comment by MaxWaldorf** [comment]
Is auth-duo of extension active in the container?

If yes, unless there is a specific enablement process, not sure what can be done on my side...

Have you checked on an official guacamole version?

**Comment by ShlomiD83** [comment]
> Is auth-duo of extension active in the container?
> 
> If yes, unless there is a specific enablement process, not sure what can be done on my side...
> 
> Have you checked on an official guacamole version?

I can't connect to the container when duo is enabled in the compose file. 

Tried official Guacamole image but didn't have luck getting it going, getting the same error..

**Comment by MaxWaldorf** [comment]
Thern maybe contact the guacamole team...
I'm not going going to have much more help myself at this point... :(
