### ISSUE TITLE
totp is not working

### ISSUE THREAD

**Issue by fate8383** [flcontainers/guacamole#68]
I have tried all the recent 1.5 versions (and latest) and also testing tag all the composes working fine. I do not have logs as I used to have like login IPs, and totp is absolutely not working at all. RPI4 arm64 and VM AMD via portioner. All tried fresh installs and tried -e timezone with or without cannot validate totp.

**Comment by MaxWaldorf** [comment]
A new version of 1.5.0 is compiling
I tried to see what could be the issu but no idea so far...

**Comment by fate8383** [comment]
> A new version of 1.5.0 is compiling
> I tried to see what could be the issu but no idea so far...

tried from new docker hub flcontainers/guacamole latest and it is not working still, no logs no totp

**Comment by MaxWaldorf** [comment]
I use totp on my current install and it is working fine...

I'll try a fresh one to see...

**Comment by MaxWaldorf** [comment]
Tested locally...
Works 100% on amd64 and arm64.

Somethng isn't right with your setup...

**Comment by YannicNoe** [comment]
Hey, I'm from germany and I could get totp to work. I noticed, that the log Time did not match witch my local time. So I setup the Raspberry to use the correct timezone and bound /etc/timezone and /etc/localtime from the host to the same place in the container. I did it as read only.
TZ Environment variable did not work at all and I suggest to document the solution if it does work for others too.

**Comment by fate8383** [comment]
> Hey, I'm from germany and I could get totp to work. I noticed, that the log Time did not match witch my local time. So I setup the Raspberry to use the correct timezone and bound /etc/timezone and /etc/localtime from the host to the same place in the container. I did it as read only.
> TZ Environment variable did not work at all and I suggest to document the solution if it does work for others too.

yeah clearly this is timezone issue like all totp failures would lead you to :) thanks. as I mentioned in the previous tickets as well. I thought -e TZ works, but I noticed just now only updates the GUA app time  so not the postgress and being postgress always in UTC breaks totp. Good catch with bounding etc/timezone, not that I will do it but it should be documented. I have tried 3 different cpus, 3 diferent timezones all fails. I don't have an instance in UTC to test, that might have worked just fine.

**Comment by MaxWaldorf** [comment]
check dev branch and Testing image (currently compiling)...

**Comment by MaxWaldorf** [comment]
New container pushed...
Should resolve incident

**Comment by fate8383** [comment]
> New container pushed...
> 
> Should resolve incident

Cannot test now but I see latest tag is 5 hours old, I will use the testing tag? Which is 25 min ego

**Comment by MaxWaldorf** [comment]
it take an hour to compile on public runners...

Shouldn't take too long from there

**Comment by fate8383** [comment]
> it take an hour to compile on public runners...
> 
> Shouldn't take too long from there

TOTP with tag testing does not work,  tag latest does not work. with -e TZ or without as fresh install.

**Comment by fate8383** [comment]
> > it take an hour to compile on public runners...
> 
> > 
> 
> > Shouldn't take too long from there
> 
> 
> 
> TOTP with tag testing does not work,  tag latest does not work. with -e TZ or without as fresh install.

Tested again throughly and even other composes from docker hub. It seems like my distant amd instant is the only one not working with totp all others are working such as arms. I accept think of why but instant is on another time zone and I am in another I doubt that this is the problem but I even tried bringing all to the same time zone and it still says verification failed try again. This is more like me problem I think. Unless there is something with the amd. Otherwise it works thanks. Still missing the logged in IPs logs though in all type of instances.
