### ISSUE TITLE
Potential Memory Leak in Container

### ISSUE THREAD

**Issue by SnowyJaguar1034** [flcontainers/guacamole#73]
Hi, So I spun up a Guacamole container using your docker commands, and it appears to be regularly exiting with error code 137 without reporting an error in the logs. According to my Googling this indicates that the container is running out of memory; however, I only have one VNC connection setup so far and the Container Host VM has 5GB of RAM and it's only really using 50% of it so I'm suspecting there might be a memory leak somewhere in the container.

Sorry if this issue doesn't follow your standards

**Comment by MaxWaldorf** [comment]
running for 14 days here with a memory consumption of 480Mi

I don't think this unreasonnable...

**Comment by MaxWaldorf** [comment]
No feedback closing

**Comment by SnowyJaguar1034** [comment]
> running for 14 days here with a memory consumption of 480Mi
> 
> I don't think this unreasonnable...

How odd, I'm still seeing the container randomly crash for no apparent reason so I'm not sure what's going on.
