### ISSUE TITLE
How to set a fixed Port for guacd

### ISSUE THREAD

**Issue by edu8** [flcontainers/guacamole#75]
Hi there,

I used a different docker image for guacamole but the one i used for years is not longer maintained. So i switched to this one. The old one is on version 1.3 and updating doesn't work somehow. So i get rid of the old data to start from scratch. The container seems to be running but I can't connect. I expect the deamon to listen to port 8080 but instead it seems to listen on different ports in the 4000 area. This is what netstat on the container shows me:

netstat -tunlp                                                                                                                                                          
Active Internet connections (only servers)                                                                                                                                                            
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name                                                                                                      
tcp        0      0 0.0.0.0:4822            0.0.0.0:*               LISTEN      20/guacd                                                                                                              
tcp        0      0 127.0.0.1:5432          0.0.0.0:*               LISTEN      -                                                                                                                     
udp        0      0 0.0.0.0:8472            0.0.0.0:*                           -

The conainer is up and running and doesn't log any errors but these two:
touch: /opt/tomcat/logs/catalina.out: Permission denied
/opt/tomcat/bin/catalina.sh: line 504: can't create /opt/tomcat/logs/catalina.out: Permission denied

As the log ends with "container started" I don't think that this is a problem. But somehow it doesn't work. This is how the container is created.

docker run -d --name=guacamole \
-p 8948:8080 \
-e PUID=1026 \
-e PGID=100 \
-e TZ=Europe/Berlin \
-e EXTENSIONS="auth-totp" \
-v /volume1/docker/guacamole:/config \
--restart always \
flcontainers/guacamole

**Comment by edu8** [comment]
When leaving the container running it logs the following a few times:
guacd[21]: ERROR:	Guacamole protocol violation. Perhaps the version of guacamole-client is incompatible with this version of guacd?

**Comment by MaxWaldorf** [comment]
don't use PUID PGUID
