### ISSUE TITLE
Tomcat error with version 1.5.0

### ISSUE THREAD

**Issue by erik-de-bont** [flcontainers/guacamole#76]
I am getting the tomcat error (see screenshot) with the docker container  flcontainers/guacamole:latest (and testing) version. The previous version maxwaldorf/guacamole:1.4.3 is working fine.

![error](https://user-images.githubusercontent.com/71345042/235326848-0d1bfa02-99d5-4592-9a98-5ee246479bc4.png)

**Comment by MaxWaldorf** [comment]
Are you running PUID or PGID parameters?

**Comment by erik-de-bont** [comment]
No I am not using PUID or PGID paramaters. I did manage to get it work via a workaround.

```
docker run -d \
  --name=guacamole \
  -e TZ="Europe/Amsterdam" \
  -e EXTENSIONS="auth-totp" \
  -p 8080:8080 \
  -v /volume1/docker/guacamole/config:/config \
  -v /volume1/docker/guacamole/opt/tomcat/logs:/opt/tomcat/logs \
  -v /etc/localtime:/etc/localtime:ro \
  --restart unless-stopped \
flcontainers/guacamole:latest
```
I have mounted the /opt/tomcat/logs to my NAS volume, and set the owner to 1000 and group to 1000. This workaround works.

**Comment by MaxWaldorf** [comment]
Ok, then you're doing something wrong with your mount for the simple reason that rights are not good on your folder for the logs...

Connect from the container and change the rights to "tomcat" user... (which is not the same between host and guest)

I will reject the bug as this is not an intended use of that container and I assume people understand the concept of proper rights management when mounting folders.

**Comment by erik-de-bont** [comment]
I think it is a bug. And what you suggested is exactly what I did, since the tomcat user had id 1000. The reason I had to mount /opt/tomcat/log to external storage  since the tomcat account does not seem to be able to write to that folder within the container.

![image](https://user-images.githubusercontent.com/71345042/235376521-4bab64c3-4ee6-460d-bbea-853d93da13cc.png)

**Comment by MaxWaldorf** [comment]
Sorry but I don't how this is a bug given that the docker file stipulate ownership of the folder to the tomcat user.

So unless you have a specific legacy config or host config, this is not supposed to happen.

Check the docker file and see if you have ways to fix it based on your situation.

**Comment by clb92** [comment]
I'm having the same problem after upgrading from `maxwaldorf/guacamole:1.4.0` on my Synology. I've also created a brand new container with empty config folder, and same thing happens. On another server (running Unraid) the problem did not happen.

@erik-de-bont Do you happen to run this on a Synology too?

**Comment by clb92** [comment]
My solution was to shell in as root, `touch /opt/tomcat/logs/catalina.out`, `chmod 777 /opt/tomcat/logs/catalina.out` and restart the container, now it starts properly.

**Comment by erik-de-bont** [comment]
@clb92  I had the same issue on a Synology NAS. After that fix I still has issues with the first time login of guacadmin, after that I switched to another [image](https://hub.docker.com/r/jwetzell/guacamole) which didn´t had the issue and seems to work better with the docker version of Synology.

**Comment by MaxWaldorf** [comment]
I tried to help with the newest dev version of my container...

Let me know if that works in a few hours

**Comment by clb92** [comment]
>newest dev version

That'll be the `flcontainers/guacamole:testing` image, correct?

I would test it now, but I'm currently rebuilding my RAID array on that server, so it'll have to wait a bit.

**Comment by clb92** [comment]
Sorry for not testing it earlier, I've been super busy and stressed out these last months, but there's no change for me with dev version, unfortunately.
