### ISSUE TITLE
Updating to latest container broke TOTP

### ISSUE THREAD

**Issue by stb109** [flcontainers/guacamole#82]
I've recently updated to the 1.5.2 container without changing anything in my docker-compose file and now I am no longer prompted to enter my 2fa after signing in. It simple logs me in and I can view my connections. Is there something I need to change?

**Comment by snodemon540** [comment]
I am observing the same behavior during an update from 1.5.0 additionally, 1.5.2 is ignoring the customized logon image.

**Comment by Iggloovortex** [comment]
issue is because container is still looking for the 1.5.1.jar while the file was renamed to 1.5.2

**Comment by snodemon540** [comment]
Unfortunately, this wasn't the issue in my situation. Even after the clean install, I continue to face issues with custom branding as well. I still believe it's related to the startup.sh implementation.

**Comment by Iggloovortex** [comment]
in my digging after you got me started, i discovered /startup.sh runs another script /usr/local/bin/_startup.sh whose first step is to rm -r both /config/guacamole/extensions and extensions-available then recreate them by cp from /app/

you'd need a way to circumvent that process to keep your config i believe

**Comment by MaxWaldorf** [comment]
this delete is mandatory to deletes previous extensions when new version is set...

If you see a better way, please propose a PR to dev branch...

**Comment by masseysan** [comment]
@MaxWaldorf, I didn't want to open a new issue but is there a way the GUAC_VER variable can be set without creating an environmental variable? I'm by no means a wiz, but I do see it mentioned a great deal in the dockerfile so I can understand why it needs to be set.

Reason I bring this up is I had a similar experience when updating from 1.5.3 > 1.5.4, removing the old variable (GUAC_VER : 1.5.3) did resolve my issue and a new one (GUAC_VER : 1.5.4) was automatically generated. I do forsee this being an issue again down when the image is updated to the next version.
