### ISSUE TITLE
New User Invalid Login with TOTP

### ISSUE THREAD

**Issue by dlmservers** [flcontainers/guacamole#87]
When creating a new user following the below steps results in error "Invalid Login"

![image](https://github.com/flcontainers/guacamole/assets/138249392/c87b310d-ea27-4708-815c-5ce4fbc4c5b1)

Creating new user, entering in password/re-enter password, checking "Password Expired", checking "Change own password". Save

User logs in (success), changes password (success), sets up totp (success), then right back to login screen with error "Invalid Login". User can no longer log in with old or new password.

![image](https://github.com/flcontainers/guacamole/assets/138249392/0947b9d1-4995-4074-bd3a-a44bd09384b3)

**Comment by MaxWaldorf** [comment]
are you sure the database works?

**Comment by dlmservers** [comment]
I can log in with other already created accounts. Can recreate on fresh install of the container on a fresh install of ubuntu. Happens every time, still happening 2 months since this post.
